----------------------------------------------------------------------------------
-- Auto-generated by piskel_argb_to_vhdl_gui.py
-- Source C file       : digit_0.c
-- Frame               : 0
-- Size                : 17 x 30
-- Output              : indexed color
-- Palette mode        : Web-safe 216
-- Palette size        : 216 RGB colors, index width 8 bit(s)
-- Original RGB colors : 10
-- Remapped/quantized  : yes
-- Notes               : C input interpreted as 0xAABBGGRR. Alpha=0 pixels map to x"000000".
--
-- Palette used by this indexed sprite:
--   index   0 => RGB x"000000"  #000000
--   index   1 => RGB x"000033"  #000033
--   index   2 => RGB x"000066"  #000066
--   index   3 => RGB x"000099"  #000099
--   index   4 => RGB x"0000CC"  #0000CC
--   index   5 => RGB x"0000FF"  #0000FF
--   index   6 => RGB x"003300"  #003300
--   index   7 => RGB x"003333"  #003333
--   index   8 => RGB x"003366"  #003366
--   index   9 => RGB x"003399"  #003399
--   index  10 => RGB x"0033CC"  #0033CC
--   index  11 => RGB x"0033FF"  #0033FF
--   index  12 => RGB x"006600"  #006600
--   index  13 => RGB x"006633"  #006633
--   index  14 => RGB x"006666"  #006666
--   index  15 => RGB x"006699"  #006699
--   index  16 => RGB x"0066CC"  #0066CC
--   index  17 => RGB x"0066FF"  #0066FF
--   index  18 => RGB x"009900"  #009900
--   index  19 => RGB x"009933"  #009933
--   index  20 => RGB x"009966"  #009966
--   index  21 => RGB x"009999"  #009999
--   index  22 => RGB x"0099CC"  #0099CC
--   index  23 => RGB x"0099FF"  #0099FF
--   index  24 => RGB x"00CC00"  #00CC00
--   index  25 => RGB x"00CC33"  #00CC33
--   index  26 => RGB x"00CC66"  #00CC66
--   index  27 => RGB x"00CC99"  #00CC99
--   index  28 => RGB x"00CCCC"  #00CCCC
--   index  29 => RGB x"00CCFF"  #00CCFF
--   index  30 => RGB x"00FF00"  #00FF00
--   index  31 => RGB x"00FF33"  #00FF33
--   index  32 => RGB x"00FF66"  #00FF66
--   index  33 => RGB x"00FF99"  #00FF99
--   index  34 => RGB x"00FFCC"  #00FFCC
--   index  35 => RGB x"00FFFF"  #00FFFF
--   index  36 => RGB x"330000"  #330000
--   index  37 => RGB x"330033"  #330033
--   index  38 => RGB x"330066"  #330066
--   index  39 => RGB x"330099"  #330099
--   index  40 => RGB x"3300CC"  #3300CC
--   index  41 => RGB x"3300FF"  #3300FF
--   index  42 => RGB x"333300"  #333300
--   index  43 => RGB x"333333"  #333333
--   index  44 => RGB x"333366"  #333366
--   index  45 => RGB x"333399"  #333399
--   index  46 => RGB x"3333CC"  #3333CC
--   index  47 => RGB x"3333FF"  #3333FF
--   index  48 => RGB x"336600"  #336600
--   index  49 => RGB x"336633"  #336633
--   index  50 => RGB x"336666"  #336666
--   index  51 => RGB x"336699"  #336699
--   index  52 => RGB x"3366CC"  #3366CC
--   index  53 => RGB x"3366FF"  #3366FF
--   index  54 => RGB x"339900"  #339900
--   index  55 => RGB x"339933"  #339933
--   index  56 => RGB x"339966"  #339966
--   index  57 => RGB x"339999"  #339999
--   index  58 => RGB x"3399CC"  #3399CC
--   index  59 => RGB x"3399FF"  #3399FF
--   index  60 => RGB x"33CC00"  #33CC00
--   index  61 => RGB x"33CC33"  #33CC33
--   index  62 => RGB x"33CC66"  #33CC66
--   index  63 => RGB x"33CC99"  #33CC99
--   index  64 => RGB x"33CCCC"  #33CCCC
--   index  65 => RGB x"33CCFF"  #33CCFF
--   index  66 => RGB x"33FF00"  #33FF00
--   index  67 => RGB x"33FF33"  #33FF33
--   index  68 => RGB x"33FF66"  #33FF66
--   index  69 => RGB x"33FF99"  #33FF99
--   index  70 => RGB x"33FFCC"  #33FFCC
--   index  71 => RGB x"33FFFF"  #33FFFF
--   index  72 => RGB x"660000"  #660000
--   index  73 => RGB x"660033"  #660033
--   index  74 => RGB x"660066"  #660066
--   index  75 => RGB x"660099"  #660099
--   index  76 => RGB x"6600CC"  #6600CC
--   index  77 => RGB x"6600FF"  #6600FF
--   index  78 => RGB x"663300"  #663300
--   index  79 => RGB x"663333"  #663333
--   index  80 => RGB x"663366"  #663366
--   index  81 => RGB x"663399"  #663399
--   index  82 => RGB x"6633CC"  #6633CC
--   index  83 => RGB x"6633FF"  #6633FF
--   index  84 => RGB x"666600"  #666600
--   index  85 => RGB x"666633"  #666633
--   index  86 => RGB x"666666"  #666666
--   index  87 => RGB x"666699"  #666699
--   index  88 => RGB x"6666CC"  #6666CC
--   index  89 => RGB x"6666FF"  #6666FF
--   index  90 => RGB x"669900"  #669900
--   index  91 => RGB x"669933"  #669933
--   index  92 => RGB x"669966"  #669966
--   index  93 => RGB x"669999"  #669999
--   index  94 => RGB x"6699CC"  #6699CC
--   index  95 => RGB x"6699FF"  #6699FF
--   index  96 => RGB x"66CC00"  #66CC00
--   index  97 => RGB x"66CC33"  #66CC33
--   index  98 => RGB x"66CC66"  #66CC66
--   index  99 => RGB x"66CC99"  #66CC99
--   index 100 => RGB x"66CCCC"  #66CCCC
--   index 101 => RGB x"66CCFF"  #66CCFF
--   index 102 => RGB x"66FF00"  #66FF00
--   index 103 => RGB x"66FF33"  #66FF33
--   index 104 => RGB x"66FF66"  #66FF66
--   index 105 => RGB x"66FF99"  #66FF99
--   index 106 => RGB x"66FFCC"  #66FFCC
--   index 107 => RGB x"66FFFF"  #66FFFF
--   index 108 => RGB x"990000"  #990000
--   index 109 => RGB x"990033"  #990033
--   index 110 => RGB x"990066"  #990066
--   index 111 => RGB x"990099"  #990099
--   index 112 => RGB x"9900CC"  #9900CC
--   index 113 => RGB x"9900FF"  #9900FF
--   index 114 => RGB x"993300"  #993300
--   index 115 => RGB x"993333"  #993333
--   index 116 => RGB x"993366"  #993366
--   index 117 => RGB x"993399"  #993399
--   index 118 => RGB x"9933CC"  #9933CC
--   index 119 => RGB x"9933FF"  #9933FF
--   index 120 => RGB x"996600"  #996600
--   index 121 => RGB x"996633"  #996633
--   index 122 => RGB x"996666"  #996666
--   index 123 => RGB x"996699"  #996699
--   index 124 => RGB x"9966CC"  #9966CC
--   index 125 => RGB x"9966FF"  #9966FF
--   index 126 => RGB x"999900"  #999900
--   index 127 => RGB x"999933"  #999933
--   index 128 => RGB x"999966"  #999966
--   index 129 => RGB x"999999"  #999999
--   index 130 => RGB x"9999CC"  #9999CC
--   index 131 => RGB x"9999FF"  #9999FF
--   index 132 => RGB x"99CC00"  #99CC00
--   index 133 => RGB x"99CC33"  #99CC33
--   index 134 => RGB x"99CC66"  #99CC66
--   index 135 => RGB x"99CC99"  #99CC99
--   index 136 => RGB x"99CCCC"  #99CCCC
--   index 137 => RGB x"99CCFF"  #99CCFF
--   index 138 => RGB x"99FF00"  #99FF00
--   index 139 => RGB x"99FF33"  #99FF33
--   index 140 => RGB x"99FF66"  #99FF66
--   index 141 => RGB x"99FF99"  #99FF99
--   index 142 => RGB x"99FFCC"  #99FFCC
--   index 143 => RGB x"99FFFF"  #99FFFF
--   index 144 => RGB x"CC0000"  #CC0000
--   index 145 => RGB x"CC0033"  #CC0033
--   index 146 => RGB x"CC0066"  #CC0066
--   index 147 => RGB x"CC0099"  #CC0099
--   index 148 => RGB x"CC00CC"  #CC00CC
--   index 149 => RGB x"CC00FF"  #CC00FF
--   index 150 => RGB x"CC3300"  #CC3300
--   index 151 => RGB x"CC3333"  #CC3333
--   index 152 => RGB x"CC3366"  #CC3366
--   index 153 => RGB x"CC3399"  #CC3399
--   index 154 => RGB x"CC33CC"  #CC33CC
--   index 155 => RGB x"CC33FF"  #CC33FF
--   index 156 => RGB x"CC6600"  #CC6600
--   index 157 => RGB x"CC6633"  #CC6633
--   index 158 => RGB x"CC6666"  #CC6666
--   index 159 => RGB x"CC6699"  #CC6699
--   index 160 => RGB x"CC66CC"  #CC66CC
--   index 161 => RGB x"CC66FF"  #CC66FF
--   index 162 => RGB x"CC9900"  #CC9900
--   index 163 => RGB x"CC9933"  #CC9933
--   index 164 => RGB x"CC9966"  #CC9966
--   index 165 => RGB x"CC9999"  #CC9999
--   index 166 => RGB x"CC99CC"  #CC99CC
--   index 167 => RGB x"CC99FF"  #CC99FF
--   index 168 => RGB x"CCCC00"  #CCCC00
--   index 169 => RGB x"CCCC33"  #CCCC33
--   index 170 => RGB x"CCCC66"  #CCCC66
--   index 171 => RGB x"CCCC99"  #CCCC99
--   index 172 => RGB x"CCCCCC"  #CCCCCC
--   index 173 => RGB x"CCCCFF"  #CCCCFF
--   index 174 => RGB x"CCFF00"  #CCFF00
--   index 175 => RGB x"CCFF33"  #CCFF33
--   index 176 => RGB x"CCFF66"  #CCFF66
--   index 177 => RGB x"CCFF99"  #CCFF99
--   index 178 => RGB x"CCFFCC"  #CCFFCC
--   index 179 => RGB x"CCFFFF"  #CCFFFF
--   index 180 => RGB x"FF0000"  #FF0000
--   index 181 => RGB x"FF0033"  #FF0033
--   index 182 => RGB x"FF0066"  #FF0066
--   index 183 => RGB x"FF0099"  #FF0099
--   index 184 => RGB x"FF00CC"  #FF00CC
--   index 185 => RGB x"FF00FF"  #FF00FF
--   index 186 => RGB x"FF3300"  #FF3300
--   index 187 => RGB x"FF3333"  #FF3333
--   index 188 => RGB x"FF3366"  #FF3366
--   index 189 => RGB x"FF3399"  #FF3399
--   index 190 => RGB x"FF33CC"  #FF33CC
--   index 191 => RGB x"FF33FF"  #FF33FF
--   index 192 => RGB x"FF6600"  #FF6600
--   index 193 => RGB x"FF6633"  #FF6633
--   index 194 => RGB x"FF6666"  #FF6666
--   index 195 => RGB x"FF6699"  #FF6699
--   index 196 => RGB x"FF66CC"  #FF66CC
--   index 197 => RGB x"FF66FF"  #FF66FF
--   index 198 => RGB x"FF9900"  #FF9900
--   index 199 => RGB x"FF9933"  #FF9933
--   index 200 => RGB x"FF9966"  #FF9966
--   index 201 => RGB x"FF9999"  #FF9999
--   index 202 => RGB x"FF99CC"  #FF99CC
--   index 203 => RGB x"FF99FF"  #FF99FF
--   index 204 => RGB x"FFCC00"  #FFCC00
--   index 205 => RGB x"FFCC33"  #FFCC33
--   index 206 => RGB x"FFCC66"  #FFCC66
--   index 207 => RGB x"FFCC99"  #FFCC99
--   index 208 => RGB x"FFCCCC"  #FFCCCC
--   index 209 => RGB x"FFCCFF"  #FFCCFF
--   index 210 => RGB x"FFFF00"  #FFFF00
--   index 211 => RGB x"FFFF33"  #FFFF33
--   index 212 => RGB x"FFFF66"  #FFFF66
--   index 213 => RGB x"FFFF99"  #FFFF99
--   index 214 => RGB x"FFFFCC"  #FFFFCC
--   index 215 => RGB x"FFFFFF"  #FFFFFF
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity digit_0_idx_rom is
    port (
        clk         : in  std_logic;
        en          : in  std_logic;
        row_addr    : in  unsigned(4 downto 0);  -- 0 to 29
        col_addr    : in  unsigned(4 downto 0);  -- 0 to 16
        color_index : out std_logic_vector(7 downto 0)
    );
end digit_0_idx_rom;

architecture Behavioral of digit_0_idx_rom is
    constant SPRITE_WIDTH  : integer := 17;
    constant SPRITE_HEIGHT : integer := 30;

    subtype index_t is std_logic_vector(7 downto 0);

    type row_t    is array (0 to SPRITE_WIDTH - 1) of index_t;
    type sprite_t is array (0 to SPRITE_HEIGHT - 1) of row_t;

    constant sprite_rom : sprite_t := (
        0 => (x"00", x"00", x"00", x"00", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"87", x"87", x"00", x"00", x"00"),
        1 => (x"00", x"00", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"87", x"00", x"00"),
        2 => (x"00", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00"),
        3 => (x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00"),
        4 => (x"00", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC"),
        5 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"87", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"87"),
        6 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        7 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        8 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        9 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        10 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        11 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        12 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        13 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        14 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        15 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        16 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        17 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        18 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        19 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        20 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        21 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        22 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        23 => (x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00", x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC"),
        24 => (x"87", x"AC", x"AC", x"AC", x"AC", x"87", x"00", x"00", x"00", x"00", x"00", x"AC", x"AC", x"AC", x"AC", x"AC", x"87"),
        25 => (x"00", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC"),
        26 => (x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00"),
        27 => (x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"00"),
        28 => (x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"87", x"00", x"00"),
        29 => (x"00", x"00", x"00", x"00", x"87", x"AC", x"AC", x"AC", x"AC", x"AC", x"AC", x"87", x"AC", x"AC", x"00", x"00", x"00")
    );

begin

    process(clk)
        variable r : integer;
        variable c : integer;
    begin
        if rising_edge(clk) then
            if en = '1' then
                r := to_integer(row_addr);
                c := to_integer(col_addr);
                if r >= 0 and r < SPRITE_HEIGHT and c >= 0 and c < SPRITE_WIDTH then
                    color_index <= sprite_rom(r)(c);
                else
                    color_index <= x"00";
                end if;
            else
                color_index <= x"00";
            end if;
        end if;
    end process;

end Behavioral;
